---
ID: "1ff5af22-d321-4cec-8044-5504854e1ba3"
Parent: "6479fd96-e4e3-4683-8543-10d06ede6ac8"
Template: "6479fd96-e4e3-4683-8543-10d06ede6ac8"
Path: /sitecore/templates/SitecoreDemo/Feature/HomePage/_FeaturedContent/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221101T101350Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aada4558-210d-4c23-a024-28ecae50b38b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221101T101429Z
